### ISSUE TITLE
Layouts broken with new layout update

### ISSUE THREAD

**Issue by emiljensen2** [dillydill123/inventory-setups#256] opened 2024-07-10 10:58 UTC
Hello, it appears inventory setup doesn't work with the new bank tag layouts update that just got released.
Stuff isn't laid out, and some items are missing which I think is due to no layout.

**Comment by emiljensen2** [comment] 2024-07-10 10:59
Well it looks like the scrollbar just doesn't accommodate the setup size.
![image](https://github.com/dillydill123/inventory-setups/assets/55587410/3ae3d2a5-d0c4-4165-a388-49ee92a35955)

**Comment by WongBater** [comment] 2024-07-10 11:30
Can confirm bank tag layouts and inventory setups are no longer working together. The actual location of these items can still be seen when hovering over empty spots as seen below the red square is indicating my mouse position.
![2024-07-10_13-29](https://github.com/dillydill123/inventory-setups/assets/105360140/39ef6952-c06d-4c9d-b8d5-9e17644eed31)

**Comment by gtjamesa** [comment] 2024-07-10 12:30
I'm also having the same issues as above and seeing the ghost items. Clicking the items and had to gear up for ToB by withdrawing everything one item at a time :facepalm: As you can see in the video, right clicking is also broken(?)

https://github.com/dillydill123/inventory-setups/assets/2078364/e6b517d1-2b5c-4e27-9615-0c32e7022e50

**Comment by ijonasb** [comment] 2024-07-10 16:58
yes this is also broken for me the same way

**Comment by dillydill123** [comment] 2024-07-10 17:10
Thanks for reporting. I think the issue is from the BTL side. The author is aware and is taking a look. I will close this issue when it has been resolved.

**Comment by RuneLiteSuggestion** [comment] 2024-07-10 20:23
> Thanks for reporting. I think the issue is from the BTL side. The author is aware and is taking a look. I will close this issue when it has been resolved.

the issue seems to have been resolved however my crystal halberd doesn't show in there anymore even with fuzzy on

**Comment by dillydill123** [comment] 2024-07-10 20:27
Issue should be resolved. Please create a new issue for any other problems.

**Closed by dillydill123** 2024-07-10 20:27 UTC
