### ISSUE TITLE
Changes are not saved

### ISSUE THREAD

**Issue by JetFlightGit** [dillydill123/inventory-setups#164] opened 2022-08-31 08:09 UTC
Hey,

i am having an issue that if I delete my old Setups or add new set ups, it always changes back the next time i log in (close runelite and open it up again). Tried removing the plugin and adding again with no sucess :(

**Comment by dillydill123** [comment] 2022-08-31 12:43
How many setups do you have?

**Comment by JetFlightGit** [comment] 2022-08-31 13:00
24,but tried deleting them all but they all came back

**Comment by dillydill123** [comment] 2022-09-01 00:09
Okay, could you send me your settings.properties file? And please try again and send me your client.log file. Also, if you are logged into RuneLite, you might have to wait a minute or two for changes to sync.

**Comment by JetFlightGit** [comment] 2022-09-02 07:07
Hey not sure what you mean with settings.properties files and client log. Where would i find that?

**Comment by dillydill123** [comment] 2022-09-02 21:41
Please try to reproduce the bug and then go to your logs folder `C:\Users\<user>\.runelite\logs` and provide the `client.log` file. You're settings.properties file will be in the .runelite folder, or it will be in one of your profiles if you are logged in to RuneLite. e.g., `C:\Users\<user>\.runelite\profiles\<email>`

**Comment by JetFlightGit** [comment] 2022-09-05 09:27
[client.log](https://github.com/dillydill123/inventory-setups/files/9488587/client.log)

https://pastebin.com/Qbwi4uK8

Hopefully this is what is needed.

**Comment by dillydill123** [comment] 2022-09-06 02:13
I don't think that's the right settings.properties because I don't see any inventory setups data. If you are using a profile in RuneLite the settings.properties will in the profiles folder. Inside the settings.properties there is a `inventorysetups.setups` line which contains your data.

That being said, the `client.log` is helpful. There is a null pointer exception and I see where it is occurring. In the migration of your old data to the new optimized data, it's running into a problem. But I wouldn't expect this problem to occur unless you had extremely old data and never logged in for quite some time. So maybe something else is the issue. If you could find the correct settings.properties this will be very helpful

**Comment by meepmorpthemarp** [comment] 2022-09-06 02:37
Hi there, sorry to piggyback off this but I'm experiencing the same issue. Old loadouts I made possibly a few years ago (can't remember exactly when) seem to non-deletable and any new setups I create are removed when I restart runelite. Looking at  your last comment I definitely have had long periods of not logging in so it could be a migration issue.

Here are the log files:


https://pastebin.com/8DPXHwC3
[client.log](https://github.com/dillydill123/inventory-setups/files/9492880/client.log)

Hope this helps.

**Comment by dillydill123** [comment] 2022-09-06 03:13
@meepmorpthemarp  I'm not seeing any inventory setup data either in your settings.properties. But I am seeing the same issue where it is failing during migration to V2 data. Can you search for your settings.properties file which contains the line `inventorysetups.setups`?

**Comment by JetFlightGit** [comment] 2022-09-06 06:34
> I don't think that's the right settings.properties because I don't see any inventory setups data. If you are using a profile in RuneLite the settings.properties will in the profiles folder. Inside the settings.properties there is a `inventorysetups.setups` line which contains your data.
> 
> That being said, the `client.log` is helpful. There is a null pointer exception and I see where it is occurring. In the migration of your old data to the new optimized data, it's running into a problem. But I wouldn't expect this problem to occur unless you had extremely old data and never logged in for quite some time. So maybe something else is the issue. If you could find the correct settings.properties this will be very helpful

Hey, will check later when I get home again. But as far as I know it is the correct settings. It has the correct username and I don't remember using any other settings folder. Will double check later thought.

That being said, this is very old Data. Stopped playing for quiet some time. Not sure if that setting is lost if you stopped playing for so long

**Comment by JetFlightGit** [comment] 2022-09-06 11:52
I just checked it again, should be the correct Server Settings File.

**Comment by dillydill123** [comment] 2022-09-06 14:46
I'm not able to reproduce the issue with the file you gave me. It has no inventory setups data in it, so I don't think it's the right one.

Even if it's old data, using the plugin before 1.14 would have fixed it. That being said, I think I have a fix for the potential problem. But I'd like to be able to reproduce the problem first and verify my solution will fix it.

**Comment by JetFlightGit** [comment] 2022-09-06 15:01
Is there a way to see where my setting file is when i have runelite open?
I do have 5 diffrent setting files in the folder but 4 have a diffrent a username since i created those so i can log in with diffrent accounts using diffrent setting. Those accounts should all have same inventory setup files though since i should of copied them over aswell

**Comment by dillydill123** [comment] 2022-09-06 15:13
For the first question I don't think so. But the correct `settings.properties` file should contain the key `inventorysetups.setups`.

**Comment by JetFlightGit** [comment] 2022-09-09 11:42
I have looked again for quiet a bit of time. But i can only find this setting properties file without the key that you are looking for in it. Not sure how to fix that.

**Comment by grechasneak** [comment] 2022-09-12 19:55
Hey having the same issues

Settings: https://pastebin.com/VWAGwQmq
Log: https://pastebin.com/fsFHi6ff

**Comment by grechasneak** [comment] 2022-09-13 03:09
Is there a way to just reset all the data associated with the plugin?

**Comment by dillydill123** [comment] 2022-09-13 03:17
Yeah, by deleting the line `inventorysetups.setups` from your `settings.properties`. I'm able to reproduce the issue so I'm gonna debug it now. Thanks for providing the files!

**Comment by dillydill123** [comment] 2022-09-13 03:48
Alright, so I've identified the bug and have made a PR to update the plugin. Hopefully it gets merged soon. Sorry for the inconvenience and thanks everyone who submitted data to help me debug. I will notify this issue once the plugin gets updated.

**Comment by dillydill123** [comment] 2022-09-13 04:07
It's been merged now so please try using the plugin in a little bit to see if you can use it now. It could take up to 30 min for the update to appear

**Comment by grechasneak** [comment] 2022-09-15 03:31
It works! Thanks man! Love the open source community haha.

**Closed** 2022-09-15 03:33 UTC
