### ISSUE TITLE
MIssing setups

### ISSUE THREAD

**Issue by Intecpsp** [dillydill123/inventory-setups#248] opened 2024-04-01 17:35 UTC
I recently went through all my setups and cleaned up the naming and replaced them with coloring ("- Melee" replaced with red color, etc.). But now I am only seeing one version of the ones that I had multiple setups for. Example: I had 3 Scurrius setups (Melee, Range, and Magic), but now I only see one magic setup. 

I found my old setups in `default-0.properties`, but don't see my new ones. Should I set them up again? How can I easily pull them from the properties file for re-import?

**Comment by dillydill123** [comment] 2024-04-14 14:58
Hi, there isn't really an easy way to get the setups from properties. I recommend mass exporting the setups to have a backup (right click the import button). Are you still having setups disappear?

**Comment by Intecpsp** [comment] 2024-04-17 23:47
No more disappearing since the initial loss, I still haven't re-imported them yet to get them back from the `.properties` file. Are setups with the same name, but different colors, considered unique? I'm wondering if that's what happened to me and why I saw them after initially doing it, but not on reopening (since they never actually saved due to a silent non-unique name error).

**Comment by dillydill123** [comment] 2024-04-18 01:00
How did you get multiple setups with the same name? The plugin by design does not allow setups with the same name.

**Comment by dillydill123** [comment] 2024-04-18 01:01
That definitely is probably why they disappeared. The name is used as a key to store the data. So multiple setups with the same name would cause some data to get overwritten,

**Comment by Intecpsp** [comment] 2024-04-18 01:12
Repro steps:

1. Have 3 setups with the below naming
    - Scurrius - Melee
    - Scurrius - Magic
    - Scurrius - Range
2. Rename (I believe this is where the issue lies, in the renaming logic) setups to drop attack style and add colors
    - Scurrius
        - Red color title
    - Scurrius
        - Blue color title
    - Scurrius
        - Green color title

The UI should allow this behavior, but doesn't appear to actually save them on the backend.

**Comment by dillydill123** [comment] 2024-04-18 01:17
Thanks for reporting! Indeed if you click on the color panel it allows you to save the name even if it's already the same name as another setup. I will get this fixed.

**Comment by dillydill123** [comment] 2024-04-18 01:18
Unfortunately as a feature, I must have unique names for setups. So those 3 scurrius setus wouldn't be allowed. You need to distinguish them in some way.

**Comment by Intecpsp** [comment] 2024-04-18 01:25
I figured as much, mainly just wanted to see if there was a way to recover them and fix whatever loophole I found for the next guy. Thank you for looking into it!

**Comment by dillydill123** [comment] 2024-04-18 05:43
I fixed the bug, it will be in the next update

**Comment by dillydill123** [comment] 2024-05-12 03:41
in v1.19

**Closed by dillydill123** 2024-05-12 03:41 UTC

**Comment by Bass-Music** [comment] 2024-05-22 21:39
If I add a new setup with a unique name, even if I've deleted some of the older ones, moved them to the top/bottom of the list, they do not appear in the work items submenu or ge IS list
