### ISSUE TITLE
Add core tag tab layout API support

### ISSUE THREAD

**Issue by YvesW** [dillydill123/inventory-setups#277] opened 2024-10-09 14:36 UTC
The core bank tag tab layout has better support for e.g. potion storage compared to the hub plugin. Thus, it'd be beneficial to swap to using the core API Adam added.

See https://github.com/runelite/runelite/commit/ee0c998621dde080c80a968bdf35e773783271d1 for the API

**Comment by dillydill123** [comment] 2024-10-10 02:12
Got it, sounds like a good time to swap probably. How much effort do you think this will take?

**Comment by YvesW** [comment] 2024-10-10 03:42
According to Adam it shouldn't be that hard to do, since he spent quite a bit of time designing the API, also based on some feedback regarding what IS currently does and might need.
Obviously that's a bit easier to say if you've made the API yourself and you're Adam, but I'm sure it's quite doable.

**Comment by dan-drews** [comment] 2024-10-14 21:14
Wondering if there's been progress on this, or if I could help out at all. I have a PR updating the bank tag layouts plugin to work with potion storage, but I really did it because I use inventory setups, not because i use the bank tag layouts plugin for any other reason. I may be better off to either wait for this or help you out if you need

**Comment by dillydill123** [comment] 2024-10-14 23:03
It's in progress at the moment. I'm talking with Adam about the core api and how to integrate it with inventory setups. So there has been good progress. Although I don't expect it to finish for a couple weeks at least.

**Comment by dan-drews** [comment] 2024-10-14 23:04
Sounds good, thank you for the update!

**Comment by dillydill123** [comment] 2024-10-26 04:40
Alright, the implementation is complete but needs more thorough testing. Is anyone willing to help me test? Ideally someone with a quiver, rune pouch, and potion storage to make sure everything works. If you'd like to test:

- First, make a back up of your profiles before running inventory setups
- Open runelite and make a testing profile that you don't mind getting messed up
- Checkout this repository
- Checkout the branch `use-core-layout-api`
- Open in intellij, right click and run `InventorySetupsPluginTest` to launch the client and plugin
- Try the new layouts.

There are a lot of changes
- Core layouts is now used. Layouts will be automatically managed when you create, remove, import, export and manipulate setups.
- Inventory setups will warn you if layouts won't work due to settings and will allow you to change them.
  - Bank tags is required to be on and Hub bank tag layouts 'useWithInventorySetups' needs to be off.
- hub Bank Tag layouts data will be migrated over on first time using the plugin, so you should keep current layouts.
- There is a setting for the default layout used when creating a setup, either Preset or ZigZag
- Right click "Show worn items" to overwrite the current layout to a preset
- You can right click the export button on a panel to export the setup to a Core Bank Tag that can be imported.

**Comment by fuzxi** [comment] 2024-10-26 04:46
> Is anyone willing to help me test? Ideally someone with a quiver, rune pouch, and potion storage to make sure everything works.

I can't test at the moment myself, but it may be helpful to know that beta worlds are currently available and allow you to simply give yourself most items, including quiver and rune pouch variants.

**Comment by dan-drews** [comment] 2024-10-26 11:11
I don't have quiver, but I have rune pouch and potion storage, I'll take a stab

**Comment by gtjamesa** [comment] 2024-10-26 12:27
Excellent thanks for this, I should be able to do some testing today or tomorrow :) 

> As an aside, is there a way that I can use the plugin hub and see how this works with my other plugins while it's pointing to the snapshot version of runelite?

You should be able to manually point to the stable pluginhub: https://github.com/runelite/runelite/wiki/Building-with-IntelliJ-IDEA#pluginhub-failing-to-load

**Comment by dan-drews** [comment] 2024-10-26 12:31
> Excellent thanks for this, I should be able to do some testing today or tomorrow :)
> 
> > As an aside, is there a way that I can use the plugin hub and see how this works with my other plugins while it's pointing to the snapshot version of runelite?
> 
> You should be able to manually point to the stable pluginhub: https://github.com/runelite/runelite/wiki/Building-with-IntelliJ-IDEA#pluginhub-failing-to-load

You're awesome, thanks for the help. And sorry I didn't get around to finishing the PR in the other plugin. It seems like using this one and AdamLayouts is probably the best approach

**Comment by dan-drews** [comment] 2024-10-26 12:40
Actually, this did not work for me. Strangely, it launched fine, but then i couldn't interact with the UI at all. Removing that flag allowed me to interact with it

**Comment by gtjamesa** [comment] 2024-10-26 12:48
Ah maybe that only works for the base client (was playing around the other day). Another place could be the runelite version in `build.gradle`

**Comment by dillydill123** [comment] 2024-10-27 06:13
Thank you @dan-drews for testing. I've made some progress and request that you test again.

> 1. If I navigate to potion storage when I have an inventory setup open, then I click on potion storage to close it, it returns me to the main bank view, but it still shows the setup name at the top as if it were open. Because of the fact that yo need to open potion storage to fill out the potion slots initially, this will probably be a common workflow when somebody first launches runelite.

Still working on this one, it's tough for me to test due to not having potion storage. If you're familiar with plugins, you could try changing when the bank search happens on my branch to trigger the layout again after the potion storage is closed. For example `onWidgetLoaded` or something like that. I would also check if this works with normal Bank Tags.

> 2. Is there a way that you could set it up to easily re-generate the layout from the inventory setup? Currently the Reload button will re-generate the layout, but personally, I would like to switch my layouts to zigzag, and it'd be nice to be able to do so without having to first withdraw everything. This is not crucial, just an idea

Yes, I wasn't so clear. You can right click the "Show worn items" in the top left of the bank and go to the auto preset layout options without having to regear if a setup is selected. And you can select setups from that menu from the bank too.
![image](https://github.com/user-attachments/assets/73b6c92e-43a8-4797-a01b-80bb22820f1e)

> 3. Modifying an existing setup that was originally setup via a custom bank tag layout can cause setups to go a little haywire. I'll include a gif below of this behavior, it's a little hard to recreate from scratch, but I can consistently recreate it by importing my original profile, and adding a 1 dose super attack potion to the layout. I believe cause comes from the fact that I am now using zigzag and was not before.

I dug into this and found that it's actually due to the fact that bank tag layouts appears to be storing placeholder IDs sometimes instead of the real item ID for the layout. This doesn't play nice with either Bank Tags or Inventory Setups. When migrating the bank tag layouts data, I'm canonicalizing the IDs so it will never be a note or placeholder. Please try this again and let me know if it works after.

> 3.1. This is very minor, but when i right-click to search for an item, i have to click into the search text at the bottom of the screen, it doesn't automatically focus to that 

That's odd. I don't have to click there to get focus. I can start searching for the item without having to click. Can you double check this and see if any chat settings are causing this? You could try modifying `updateSlotFromSearch` and add `client.getCanvas().requestFocus();` to the bottom after `itemSearch` is built and see if it does anything for you.

> 4. Fuzzy matches can be placed in strange spots. A lot of times the fuzzy match is added in the first blank space, which can be near the headgear slot. I wonder if it makes sense to put those down lower, near where additional items are

This was previously a limitation by Adams layouts. Bank Tags will add variation items to the first available slot in the layout. I asked if an option could be made to add it at the end but it was not merged with that option.

However, now I tried to take matters in to my own hands and put the fuzzy items at the bottom of the layout. Fuzzy items should appear at the end of a layout now, including when generating a preset. This will not work when editing a setup without the bank interface open, as I need the bank items to accomplish this.

The items actually part of the setup will appear at the top still. This actually also let custom variation mappings work again since they were not supported by Bank Tags. Definitely play around with this one and see if anything broken or weird behavior occurs.

> 5. Right-clicking an item and selecting remove tag doesn't do anything. I'm not sure what i expected it to do since the tag is driven by the inventory setup. I wonder if that option can be removed when it's using setups

The tag is tied to the setup so ideally nobody should be clicking remove-tag. Removing the tag will cause the item to disappear in the layout, but Inventory Setups will regenerate that item in the layout if the setup is modified. I would need to ask Adam to add that option of removing tags since it's dependent on Bank Tags.

> 6. Would it be possible to give the option to add a bank tag tab for the inventory setup? I know you can export it, but it'd b neat if you could optionally add a new tag that stays in sync with the layout

Not looking to add this, the "Show worn items" button displaying the setups should suffice and I'd prefer to keep inventory setups separate from bank tags. 

> 7. If you add a _second_ rune pouch to your setup for some reason (By right-clicking a square and searching) then you remove it, the runes from the rune pouch disappear from the setup

A while ago I had a lot of code to make sure the inventory didn't have multiple quivers or rune pouches or things like that. It started to become complicated so I decided to just remove all those checks and allow the user to have undefined setups. This happens because I never accounted for someone to have two pouches. When removing a pouch it always will delete the runes without checking. Not worth changing that, but hopefully this gives some insight.

> 8. This might be a comment for the main runelite layouts plugin, but I wanted to call out that in this PR: [Allow Potion Storage to work with Bank Tag Layouts Resolves #99 geheur/bank-tag-custom-layouts#102](https://github.com/geheur/bank-tag-custom-layouts/pull/102) @gtjamesa was able to get potions to render prior to opening potion storage. It just had to do with moving where the potions were cached. [geheur/bank-tag-custom-layouts@a0270ae](https://github.com/geheur/bank-tag-custom-layouts/commit/a0270ae00010f1e0909ebac2f8c24d1f651ca16d) It might be worth looking at that change in runelite itself

I'd recommend posting an issue on RuneLite or talking with Adam in discord if you wanna get that in. That would help in problem #1 I imagine?


From my end, I still need to work on point 1 but I've tried to resolve the other findings. Let me know how it goes.

**Comment by dillydill123** [comment] 2024-10-28 00:42
I've pushed a another set of bugfixes, changes, and improvements:

- Better handling of the patch notes panel + layout warning panel working together.
- Better handling when a user switches a profile
- Don't set the bank title if an active layout is not present. This hopefully will stop the title from being set when potion storage is clicked on and off. It would be great if we could refilter but unsure how to do that yet.
- Updated the README! I went through and redid a lot of the readme gifs and pics so there's a more up-to-date guide on Inventory Setups with these changes.
- Couple of null fixes regarding the config

Some things left to do/consider (barring other bugs found):
- Need to update the patch notes panel to display proper update news.
- Still need to test with actual Bank Tag Layouts installed. Unsure if setting the configuration is enough to make it work
- The tag marker for inventory setups is quite long - `___inventorysetup___<hash_of_name>`. Might be worth reducing the size of this. It's supposed to be an implementation detail but users can see it if they click `edit-tags` on an item. Thinking of possibly `_is_<hash>` or `_is_<first eight of hash>`?

I feel it's very close to completion. Any testing/feedback is helpful.

**Comment by gtjamesa** [comment] 2024-10-28 16:13
1. I think the clarity of the patch notes panel can be improved by adding double quotes around the plugin names (i.e. `Hub Plugin "Bank Tag Layouts"`) as there's a lot of "bank" and "tag" being thrown around and it seems somewhat confusing (*to me at least*)
2. BTL -> adamlayout conversions:
	- Works perfectly across all my setups
	- The other day I purchased Torva platelegs (*yay!*) and updated the item across all setups, so my most used setups have already been re-laid out, but I've noticed a slight difference between BTL/adamlayouts: [BTL](https://i.imgur.com/bEEHPPa.png) / [adamlayouts](https://i.imgur.com/53QHms7.png). Note that I have not reapplied the zigzag in either case, but just an observation that adamlayouts is keeping my tassets placeholder
3. Auto layouts:
	- Switching between preset/zigzag works seamlessly 
	- The current implementation has fixed a pain point with BTL where running the auto-layout again would not only reset the "additional filtered items" (AFI) section, but would introduce duplicates that I would have to manually clear out. I have a couple of low-priority QOL suggestions for this area:
		- If the set of AFI items exactly matches those already in the layout, can we skip regenerating this section? This may be an adamlayouts change so DW
		- Alternately could we have the option to re-order the [side panel](https://i.imgur.com/x1K0cRq.png) similarly to how you re-order setups within a section? If you right click an item in the bank and select "Add to AFI", it seems to get inserted into a random slot (alphabetical?)
4. Potion storage
	- Potions are not being loaded until after PS has been opened
	- With a fresh client/bank open, right-clicking and selecting "Release" on the placeholder will trigger the actual quantities to be displayed
	- I've noticed a change in the adamlayouts behaviour on a vanilla (non-setups) tab. On a fresh open (with a layout enabled), the potions are now not being loaded immediately (2), but when I click to a different tag and then back, they load in (3). [1](https://i.imgur.com/660iB1r.png) / [2](https://i.imgur.com/MOur8Ti.png) / [3](https://i.imgur.com/SQejGFR.png). This may also be causing the potions not be loaded for a setup.
		- Open RL/login -> open bank -> click inv setup -> potions not loaded -> close setup -> open again -> potions loaded ([video](https://streamable.com/s1q6tm))
		- Open RL/login -> click inv setup -> open bank -> potions loaded ([video](https://streamable.com/blzzvi))
5. @dan-drews testing notes:
	- point 1 is definitely fixed
6. Is it possible to add a right-click open to a bank tag to convert BTL -> adamlayouts? or is that too far outside of the scope of this integration? Just asking because you are
7. There has been a bug when opening the rune pouch that would show random items from your bank. I can't seem to reproduce this so it must have been a Hub BTL bug. https://github.com/geheur/bank-tag-custom-layouts/issues/94
8. adamlayouts
	1. How on earth do you add a tag to a potion that's already in storage haha

Note: *My screen recorder has completely borked so I can't provide any GIFs, sorry!*

Note 2: sorry if the notes are totally out of order I was just writing things down as I found them

**Comment by dillydill123** [comment] 2024-10-28 16:33
Thank you @gtjamesa:

1. I will try to improve the language
2. The tassets should not appear in the layout if they are not part of the setup. Could you give me a reproduceable set of steps so I can look into this? Seems like a bug. Please confirm that tassets were not in your setup.
3. I can manipulate the preset layouts but for now I'm going to leave the behavior as is. For your second point, Unfortunately I made the dumb decision to use a map instead of a list for AFI a long time ago. This has bitten me multiple times, including now where the order appears random. I might be able to improve the behavior by using a `LinkedHashSet` but I cannot allow moving of the items in the panel yet. You can move them in the layout.
4. Any potion storage behavior is completely on adamlayouts so any feature requests will have to be taken to core runelite. Maybe  on inventory setup startup we can do something to "cache" the potion storage but I'm unsure how it actually works. Noted
5. Nice
6. Yes this feature exists already, right click the export button on a setup and you'll see an export to Bank Tags option. There is a gif in the import/export section of the README.
7. Glad to see that's fixed with this
8. Could you give more details? Is this related to inv setups + adamlayouts or just adamlayouts?

From my side I'd like you to mainly provide reproducible steps from #2. Since that seems like a bug blocking release of this.

**Comment by gtjamesa** [comment] 2024-10-28 17:12
> 2. The tassets should not appear in the layout if they are not part of the setup. Could you give me a reproduceable set of steps so I can look into this? Seems like a bug. Please confirm that tassets were not in your setup.

Here is the BTL layout and Setups export from my regular (non-dev) client/profile. I did previously have Bandos tassets in the setup, but I swapped them with `shift+right-click -> Update ALL slots from equipment`

```
banktaglayouts.inventory_setups_layout_Araxxor=25901\:0,29801\:1,11832\:2,22981\:3,28307\:4,26386\:5,11212\:6,21295\:8,22325\:9,13239\:11,19484\:12,19481\:16,2434\:17,28951\:18,2434\:19,13441\:20,2434\:21,385\:22,2434\:23,13441\:24,23685\:25,13441\:26,23733\:27,13441\:28,2434\:29,385\:30,29824\:31,385\:32,385\:33,13652\:34,385\:35,25818\:36,8013\:37,385\:40,385\:41,385\:42,566\:43,12625\:44,27281\:45,554\:48,565\:49,564\:50,560\:51,23694\:56,385\:57,24709\:58,29782\:61,361\:62,21003\:63,23742\:64,13441\:65,12631\:66,29134\:70,29784\:71


{"inventory":[{"id":19481,"name":"Heavy ballista","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":13441,"name":"Anglerfish","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":2434,"name":"Prayer potion(4)","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":23685,"name":"Divine super combat potion(4)","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":28951,"name":"Dizana\u0027s quiver","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":13441,"name":"Anglerfish","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":2434,"name":"Prayer potion(4)","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":23733,"name":"Divine ranging potion(4)","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":13441,"name":"Anglerfish","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":13441,"name":"Anglerfish","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":2434,"name":"Prayer potion(4)","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":2434,"name":"Prayer potion(4)","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":385,"name":"Shark","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":385,"name":"Shark","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":2434,"name":"Prayer potion(4)","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":29824,"name":"Extended anti-venom+(4)","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":385,"name":"Shark","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":385,"name":"Shark","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":385,"name":"Shark","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":385,"name":"Shark","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":13652,"name":"Dragon claws","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":385,"name":"Shark","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":385,"name":"Shark","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":566,"name":"Soul rune","quantity":2000,"fuzzy":false,"stackCompare":"None"},{"id":25818,"name":"Book of the dead","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":12625,"name":"Stamina potion(4)","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":8013,"name":"Teleport to house","quantity":17,"fuzzy":false,"stackCompare":"None"},{"id":27281,"name":"Divine rune pouch","quantity":1,"fuzzy":false,"stackCompare":"None"}],"equipment":[{"id":25900,"name":"Tztok slayer helmet (i)","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":21295,"name":"Infernal cape","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":29801,"name":"Amulet of rancour","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":22325,"name":"Scythe of vitur","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":11832,"name":"Bandos chestplate","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":-1,"name":"null","quantity":0,"fuzzy":false,"stackCompare":"None"},{"id":-1,"name":"null","quantity":0,"fuzzy":false,"stackCompare":"None"},{"id":26386,"name":"Torva platelegs","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":-1,"name":"null","quantity":0,"fuzzy":false,"stackCompare":"None"},{"id":22981,"name":"Ferocious gloves","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":13239,"name":"Primordial boots","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":-1,"name":"null","quantity":0,"fuzzy":false,"stackCompare":"None"},{"id":28307,"name":"Ultor ring","quantity":1,"fuzzy":false,"stackCompare":"None"},{"id":19484,"name":"Dragon javelin","quantity":290,"fuzzy":false,"stackCompare":"None"}],"rune_pouch":[{"id":554,"name":"Fire rune","quantity":15918,"fuzzy":false,"stackCompare":"None"},{"id":565,"name":"Blood rune","quantity":15964,"fuzzy":false,"stackCompare":"None"},{"id":564,"name":"Cosmic rune","quantity":15993,"fuzzy":false,"stackCompare":"None"},{"id":560,"name":"Death rune","quantity":16000,"fuzzy":false,"stackCompare":"None"}],"quiver":[{"id":11212,"name":"","quantity":5847,"fuzzy":false,"stackCompare":"None"}],"additionalFilteredItems":{"385":{"id":385,"name":"Shark","quantity":1,"fuzzy":false,"stackCompare":"None"},"13441":{"id":13441,"name":"Anglerfish","quantity":1,"fuzzy":false,"stackCompare":"None"},"24709":{"id":24709,"name":"Hallowed crystal shard","quantity":1,"fuzzy":false,"stackCompare":"None"},"29782":{"id":29782,"name":"Spider cave teleport","quantity":1,"fuzzy":false,"stackCompare":"None"},"12631":{"id":12631,"name":"Stamina potion(1)","quantity":1,"fuzzy":false,"stackCompare":"None"},"29784":{"id":29784,"name":"Araxyte venom sack","quantity":1,"fuzzy":false,"stackCompare":"None"},"361":{"id":361,"name":"Tuna","quantity":1,"fuzzy":false,"stackCompare":"None"},"21003":{"id":21003,"name":"Elder maul","quantity":1,"fuzzy":false,"stackCompare":"None"},"23742":{"id":23742,"name":"Divine ranging potion(1)","quantity":1,"fuzzy":false,"stackCompare":"None"},"23694":{"id":23694,"name":"Divine super combat potion(1)","quantity":1,"fuzzy":false,"stackCompare":"None"},"29134":{"id":29134,"name":"Cooked dashing kebbit","quantity":1,"fuzzy":false,"stackCompare":"None"}},"name":"Araxxor","notes":"","highlightColor":"#FFFF0000","highlightDifference":true,"filterBank":true,"unorderedHighlight":false,"spellBook":3,"favorite":false,"iconID":29838}
```

> 3. I can manipulate the preset layouts but for now I'm going to leave the behavior as is. For your second point, Unfortunately I made the dumb decision to use a map instead of a list for AFI a long time ago. This has bitten me multiple times, including now where the order appears random. I might be able to improve the behavior by using a `LinkedHashSet` but I cannot allow moving of the items in the panel yet. You can move them in the layout.

Understood, no worries. Figured it was worth flagging since the plugin is getting somewhat of an overhaul

> 4. Any potion storage behavior is completely on adamlayouts so any feature requests will have to be taken to core runelite. Maybe  on inventory setup startup we can do something to "cache" the potion storage but I'm unsure how it actually works. Noted

From my testing of @dan-drews BTL potion storage integration, I noted that the potion storage caches the potions after the bank has finished building. I'm not sure of the specifics of the inventory setups implementation, but I notice that `doBankSearch()` is called in `BANKMAIN_INIT`. I'll have a play around to see if moving to `BANKMAIN_FINISHBUILDING` loads the cached potions immediately. Failing that, perhaps we can merge a new event into core that you can listen to and re-layout once the potions have been cached

See also https://github.com/runelite/runelite/blob/6b6f796bfdfdf7572d8d29fcfa5028da580d960e/runelite-client/src/main/java/net/runelite/client/plugins/banktags/tabs/LayoutManager.java#L583-L606

> 6. Yes this feature exists already, right click the export button on a setup and you'll see an export to Bank Tags option. There is a gif in the import/export section of the README.

Excellent thanks!

> 8. Could you give more details? Is this related to inv setups + adamlayouts or just adamlayouts?

This was just an observation of adamlayouts from testing the plugin - I'll go ahead and make an issue on the RL repo, because if the option is there, its unintuitive (or I'm slow)

**Comment by dillydill123** [comment] 2024-10-29 00:19
After some testing I found there was a possible null pointer exception when updating all items. So I've fixed that. That may have been the cause perhaps. I've also fixed some other bugs and made other small changes, and added the patch notes panel and bumped the setup version. Please give it a try.

**Comment by Jellicott1** [comment] 2024-11-01 23:33
Firstly, thanks for implementing this, it will be a huge QoL upgrade to potion storage. Secondly, I just tried running this branch and a couple of points I noticed:

1. Running with BTL active but invent layouts option unticked caused some problems where it seemed to lose all layout info and using the auto layout caused it to appear that many of my items were a max cash quantity of stack and they moved around when I hovered over them. Disabling the BTL plugin fixed this immediately. 
2. It seems to be working fine with quiver and rune pouch (couldn't see if anyone above had tested it). 
3. All potions seem to appear as whichever dose quantity is selected in potion storage, so it doesn't seem possible to have multiple different dose quantities active simultaneously. This may well be a limitation of the potion storage, but if it's possible to set some way of changing the dose available without navigating to the potion storage that would be great. Though I suspect as you mention above this may be an issue for adamlayouts.
4. I did have an issue where when right-clicking on an item in the layout a "Placeholder" option appeared which seemed to be functioning identically to "Withdraw-X". Though having gone in and out of a few layouts I am unable to reproduce this behaviour.

Can't wait to see this on the main branch!

**Comment by dillydill123** [comment] 2024-11-02 03:34
Thank you @Jellicott1 for the test. If you could try giving reproducible steps for 1 and 4 that would be really helpful. 

With point 1 we can contact BTL owner and have them update it so it’s completely disabled with inventory setups after this initial release of integration with the core layouts.

I think I will target the initial release with core layouts this week. There may still be some smaller bug fixes needed but I don’t see any critical issues.

**Comment by gtjamesa** [comment] 2024-11-02 11:23
> After some testing I found there was a possible null pointer exception when updating all items. So I've fixed that. That may have been the cause perhaps. I've also fixed some other bugs and made other small changes, and added the patch notes panel and bumped the setup version. Please give it a try.

Hey, apologies for the delay. I'm away at the moment and couldn't remember the steps to get IntelliJ set up with flatpak RuneLite (it's quite convoluted). Should be up and running now, so I can take another look.

Just to elaborate a bit on the "Replace ALL" problem: I'd executed the replace all prior to running the dev branch, so this would have been using BTL/Setups. When running AL/Setups in dev, the tassets were still being displayed when it didn't exist in the Setup anymore. Is this related to the BTL conversion as opposed to adamlayouts?

**Comment by Jellicott1** [comment] 2024-11-02 14:29
Hi,

I've attached an short video the bug with BTL. To reproduce, turn BTL on with inventory setups option unclicked and open a layout, withdraw the items to your invent/equipped, leaving some in the bank and click preview auto layout. Move your mouse around the layout as in the video. NOTE: It isn't showing the incorrect item stacks as before, and I can't seem to reproduce this.

https://github.com/user-attachments/assets/f5bc3430-8fe2-407c-9818-86c2a03b5245

As before, disabling the BTL plugin solves this.

As for point 4, I can't reproduce the exact issue, however with the same setup as above, instead of a "Placeholder" option, I do get two "Duplicate-Item" options, the second one works as intended and the first one causes a seemingly random item to be duplicated instead. See the attached video below: 

https://github.com/user-attachments/assets/441362f3-5949-48e0-8e2b-1d35eab84998

Agreed that these are not pressing issues though if you intend to get BTL integration with Invent setups removed.

**Comment by Jellicott1** [comment] 2024-11-02 14:37
Interestingly, having turned BTL off again and opened the same layout, all of the random items have now turned back into the correct item (in this case the buckler) and of course, the rest of the layout is now all in the correct place.


> As for point 4, I can't reproduce the exact issue, however with the same setup as above, instead of a "Placeholder" option, I do get two "Duplicate-Item" options, the second one works as intended and the first one causes a seemingly random item to be duplicated instead. See the attached video below:

**Comment by dillydill123** [comment] 2024-11-02 20:11
Ah, that preview layout button should not be used anymore. The preview layout is done from right clicking the “show worn items” in the top left in the bank with a setup selected. I will discuss with Hub BTL owner if that button can be hidden.

I think I will update the message to suggest turning off and uninstalling hub BTL more aggressively.

**Comment by dillydill123** [comment] 2024-11-02 20:13
> > After some testing I found there was a possible null pointer exception when updating all items. So I've fixed that. That may have been the cause perhaps. I've also fixed some other bugs and made other small changes, and added the patch notes panel and bumped the setup version. Please give it a try.
> 
> Hey, apologies for the delay. I'm away at the moment and couldn't remember the steps to get IntelliJ set up with flatpak RuneLite on my laptop (it's quite convoluted). Should be up and running now, so I can take another look.
> 
> Just to elaborate a bit on the "Replace ALL" problem: I'd executed the replace all prior to running the dev branch, so this would have been using BTL/Setups. When running AL/Setups in dev, the tassets were still being displayed when it didn't exist in the Setup anymore. Is this related to the BTL conversion as opposed to adamlayouts?
> 
> Edit: the BTL config and Setup export in my previous post are from my live (non-dev) RuneLite profile. It may have to be copied into a new profile with BTL enabled to trigger the conversion?
> 
> PS: new update panel text is spot on 👍

Yes it might be some problem with the conversion from hub BTL to Adam layouts :(. If you could try to reproduce it again that would be helpful. But the migration is a best effort so I’m not so worried. With auto layouts it’s easy to reset to a new layout

**Comment by dillydill123** [comment] 2024-11-07 03:27
The update is live now. I'm closing this issue. Please create a new issue for any other findings or bugs.

**Closed by dillydill123** 2024-11-07 03:27 UTC
