### ISSUE TITLE
Setups disappeared randomly

### ISSUE THREAD

**Issue by evprkr** [dillydill123/inventory-setups#116] opened 2021-10-05 19:46 UTC
I've had setups made for over a year, several of them. Today I went to add a new one and noticed that they're all gone. I've been signed in and synced on RuneLite with the same account forever, none of my other plugins have wiped settings (that I've noticed)

I'm sure this isn't reversible, just wanted to let someone know it happened to me.

**Comment by dillydill123** [comment] 2021-10-05 20:17
That's concerning. Do you have a backup of your settings? 

Check C:\Users\<users>\.runelite\profiles\

**Comment by dillydill123** [comment] 2021-10-06 03:07
Could you provide the line in the settings "inventorysetups.setups" which contains the setups? Or give the entire file for the settings.properties?

My fear at the moment is that it's a Mac issue and I cannot debug because I'm on windows. But I can try to reproduce with your setups.

**Comment by evprkr** [comment] 2021-10-06 03:10
Question, would I be looking into the profile folder for the login name of the account, or the email address associated with RuneLite? Because the email folder is where I found the settings.properties file, but the folder for my actual login account is empty.

Here's that entire segment:
`inventorysetups.setups=[{"inventory"\:[{"id"\:9185.0,"name"\:"Rune crossbow","quantity"\:1.0,"fuzzy"\:false},{"id"\:11664.0,"name"\:"Void ranger helm","quantity"\:1.0,"fuzzy"\:false},{"id"\:3016.0,"name"\:"Super energy(4)","quantity"\:1.0,"fuzzy"\:false},{"id"\:952.0,"name"\:"Spade","quantity"\:1.0,"fuzzy"\:false},{"id"\:8839.0,"name"\:"Void knight top","quantity"\:1.0,"fuzzy"\:false},{"id"\:8840.0,"name"\:"Void knight robe","quantity"\:1.0,"fuzzy"\:false},{"id"\:3016.0,"name"\:"Super energy(4)","quantity"\:1.0,"fuzzy"\:false},{"id"\:772.0,"name"\:"Dramen staff","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:2434.0,"name"\:"Prayer potion(4)","quantity"\:1.0,"fuzzy"\:false},{"id"\:2434.0,"name"\:"Prayer potion(4)","quantity"\:1.0,"fuzzy"\:false},{"id"\:560.0,"name"\:"Death rune","quantity"\:922.0,"fuzzy"\:false},{"id"\:12791.0,"name"\:"Rune pouch","quantity"\:1.0,"fuzzy"\:false}],"equipment"\:[{"id"\:10828.0,"name"\:"Helm of neitiznot","quantity"\:1.0,"fuzzy"\:false},{"id"\:13122.0,"name"\:"Ardougne cloak 2","quantity"\:1.0,"fuzzy"\:false},{"id"\:10366.0,"name"\:"Amulet of magic (t)","quantity"\:1.0,"fuzzy"\:false},{"id"\:12658.0,"name"\:"Iban\\u0027s staff (u)","quantity"\:1.0,"fuzzy"\:false},{"id"\:4091.0,"name"\:"Mystic robe top","quantity"\:1.0,"fuzzy"\:false},{"id"\:3843.0,"name"\:"Damaged book","quantity"\:1.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"null","quantity"\:0.0,"fuzzy"\:false},{"id"\:4875.0,"name"\:"Ahrim\\u0027s robeskirt 75","quantity"\:1.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"null","quantity"\:0.0,"fuzzy"\:false},{"id"\:7462.0,"name"\:"Barrows gloves","quantity"\:1.0,"fuzzy"\:false},{"id"\:19927.0,"name"\:"Guthix d\\u0027hide boots","quantity"\:1.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"null","quantity"\:0.0,"fuzzy"\:false},{"id"\:2558.0,"name"\:"Ring of dueling(5)","quantity"\:1.0,"fuzzy"\:false},{"id"\:11875.0,"name"\:"Broad bolts","quantity"\:993.0,"fuzzy"\:false}],"rune_pouch"\:[{"id"\:563.0,"name"\:"Law","quantity"\:563.0,"fuzzy"\:false,"stackCompare"\:"None"},{"id"\:554.0,"name"\:"Fire","quantity"\:14680.0,"fuzzy"\:false,"stackCompare"\:"None"},{"id"\:556.0,"name"\:"Air","quantity"\:4118.0,"fuzzy"\:false,"stackCompare"\:"None"}],"additionalFilteredItems"\:{},"name"\:"Barrows","notes"\:"Do horror from the deep and replace the d defender with an unfinished god book","highlightColor"\:{"value"\:-65536.0,"falpha"\:0.0},"highlightDifference"\:false,"filterBank"\:true,"unorderedHighlight"\:false,"spellBook"\:0.0,"Id"\:9.223372036854776E18,"favorite"\:false},{"inventory"\:[{"id"\:2448.0,"name"\:"Superantipoison(4)","quantity"\:1.0,"fuzzy"\:false},{"id"\:2448.0,"name"\:"Superantipoison(4)","quantity"\:1.0,"fuzzy"\:false},{"id"\:2448.0,"name"\:"Superantipoison(4)","quantity"\:1.0,"fuzzy"\:false},{"id"\:805.0,"name"\:"Rune thrownaxe","quantity"\:1.0,"fuzzy"\:false},{"id"\:2448.0,"name"\:"Superantipoison(4)","quantity"\:1.0,"fuzzy"\:false},{"id"\:2448.0,"name"\:"Superantipoison(4)","quantity"\:1.0,"fuzzy"\:false},{"id"\:2448.0,"name"\:"Superantipoison(4)","quantity"\:1.0,"fuzzy"\:false},{"id"\:3695.0,"name"\:"Pet rock","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:560.0,"name"\:"Death rune","quantity"\:1125.0,"fuzzy"\:false},{"id"\:554.0,"name"\:"Fire rune","quantity"\:8151.0,"fuzzy"\:false},{"id"\:2434.0,"name"\:"Prayer potion(4)","quantity"\:1.0,"fuzzy"\:false},{"id"\:772.0,"name"\:"Dramen staff","quantity"\:1.0,"fuzzy"\:false}],"equipment"\:[{"id"\:3755.0,"name"\:"Farseer helm","quantity"\:1.0,"fuzzy"\:false},{"id"\:13121.0,"name"\:"Ardougne cloak 1","quantity"\:1.0,"fuzzy"\:false},{"id"\:10366.0,"name"\:"Amulet of magic (t)","quantity"\:1.0,"fuzzy"\:false},{"id"\:12658.0,"name"\:"Iban\\u0027s staff (u)","quantity"\:1.0,"fuzzy"\:false},{"id"\:10564.0,"name"\:"Granite body","quantity"\:1.0,"fuzzy"\:false},{"id"\:3122.0,"name"\:"Granite shield","quantity"\:1.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"null","quantity"\:0.0,"fuzzy"\:false},{"id"\:4899.0,"name"\:"Dharok\\u0027s platelegs 75","quantity"\:1.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"null","quantity"\:0.0,"fuzzy"\:false},{"id"\:4095.0,"name"\:"Mystic gloves","quantity"\:1.0,"fuzzy"\:false},{"id"\:4097.0,"name"\:"Mystic boots","quantity"\:1.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"null","quantity"\:0.0,"fuzzy"\:false},{"id"\:2570.0,"name"\:"Ring of life","quantity"\:1.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"","quantity"\:0.0,"fuzzy"\:false}],"additionalFilteredItems"\:{},"name"\:"Budget Rex","notes"\:"","highlightColor"\:{"value"\:-65536.0,"falpha"\:0.0},"highlightDifference"\:false,"filterBank"\:false,"unorderedHighlight"\:false,"spellBook"\:0.0,"Id"\:9.223372036854776E18,"favorite"\:false},{"inventory"\:[{"id"\:2434.0,"name"\:"Prayer potion(4)","quantity"\:1.0,"fuzzy"\:false},{"id"\:2434.0,"name"\:"Prayer potion(4)","quantity"\:1.0,"fuzzy"\:false},{"id"\:2434.0,"name"\:"Prayer potion(4)","quantity"\:1.0,"fuzzy"\:false},{"id"\:2434.0,"name"\:"Prayer potion(4)","quantity"\:1.0,"fuzzy"\:false},{"id"\:2434.0,"name"\:"Prayer potion(4)","quantity"\:1.0,"fuzzy"\:false},{"id"\:2434.0,"name"\:"Prayer potion(4)","quantity"\:1.0,"fuzzy"\:false},{"id"\:2434.0,"name"\:"Prayer potion(4)","quantity"\:1.0,"fuzzy"\:false},{"id"\:2434.0,"name"\:"Prayer potion(4)","quantity"\:1.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"null","quantity"\:0.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"null","quantity"\:0.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"null","quantity"\:0.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"null","quantity"\:0.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:385.0,"name"\:"Shark","quantity"\:1.0,"fuzzy"\:false},{"id"\:3843.0,"name"\:"Damaged book","quantity"\:1.0,"fuzzy"\:false},{"id"\:995.0,"name"\:"Coins","quantity"\:1.0,"fuzzy"\:false},{"id"\:561.0,"name"\:"Nature rune","quantity"\:289.0,"fuzzy"\:false},{"id"\:1393.0,"name"\:"Fire battlestaff","quantity"\:1.0,"fuzzy"\:false}],"equipment"\:[{"id"\:11664.0,"name"\:"Void ranger helm","quantity"\:1.0,"fuzzy"\:false},{"id"\:10499.0,"name"\:"Ava\\u0027s accumulator","quantity"\:1.0,"fuzzy"\:false},{"id"\:1718.0,"name"\:"Holy symbol","quantity"\:1.0,"fuzzy"\:false},{"id"\:9185.0,"name"\:"Rune crossbow","quantity"\:1.0,"fuzzy"\:false},{"id"\:8839.0,"name"\:"Void knight top","quantity"\:1.0,"fuzzy"\:false},{"id"\:9731.0,"name"\:"Mind shield","quantity"\:1.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"null","quantity"\:0.0,"fuzzy"\:false},{"id"\:8840.0,"name"\:"Void knight robe","quantity"\:1.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"null","quantity"\:0.0,"fuzzy"\:false},{"id"\:8842.0,"name"\:"Void knight gloves","quantity"\:1.0,"fuzzy"\:false},{"id"\:3105.0,"name"\:"Climbing boots","quantity"\:1.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"null","quantity"\:0.0,"fuzzy"\:false},{"id"\:2566.0,"name"\:"Ring of dueling(1)","quantity"\:1.0,"fuzzy"\:false},{"id"\:11875.0,"name"\:"Broad bolts","quantity"\:1664.0,"fuzzy"\:false}],"additionalFilteredItems"\:{},"name"\:"Skeletal Wyverns","notes"\:"","highlightColor"\:{"value"\:-65536.0,"falpha"\:0.0},"highlightDifference"\:false,"filterBank"\:false,"unorderedHighlight"\:false,"spellBook"\:0.0,"Id"\:9.223372036854776E18,"favorite"\:false},{"inventory"\:[{"id"\:12791.0,"name"\:"Rune pouch","quantity"\:1.0,"fuzzy"\:false},{"id"\:809.0,"name"\:"Mithril dart","quantity"\:417.0,"fuzzy"\:false},{"id"\:2434.0,"name"\:"Prayer potion(4)","quantity"\:1.0,"fuzzy"\:false},{"id"\:2434.0,"name"\:"Prayer potion(4)","quantity"\:1.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"null","quantity"\:0.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"null","quantity"\:0.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"null","quantity"\:0.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"null","quantity"\:0.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"null","quantity"\:0.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"null","quantity"\:0.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"null","quantity"\:0.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"","quantity"\:0.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"","quantity"\:0.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"","quantity"\:0.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"","quantity"\:0.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"","quantity"\:0.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"","quantity"\:0.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"","quantity"\:0.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"","quantity"\:0.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"","quantity"\:0.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"","quantity"\:0.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"","quantity"\:0.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"","quantity"\:0.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"","quantity"\:0.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"","quantity"\:0.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"","quantity"\:0.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"","quantity"\:0.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"","quantity"\:0.0,"fuzzy"\:false}],"equipment"\:[{"id"\:11865.0,"name"\:"Slayer helmet (i)","quantity"\:1.0,"fuzzy"\:false},{"id"\:13122.0,"name"\:"Ardougne cloak 2","quantity"\:1.0,"fuzzy"\:false},{"id"\:1718.0,"name"\:"Holy symbol","quantity"\:1.0,"fuzzy"\:false},{"id"\:4675.0,"name"\:"Ancient staff","quantity"\:1.0,"fuzzy"\:false},{"id"\:9674.0,"name"\:"Proselyte hauberk","quantity"\:1.0,"fuzzy"\:false},{"id"\:3843.0,"name"\:"Damaged book","quantity"\:1.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"null","quantity"\:0.0,"fuzzy"\:false},{"id"\:9676.0,"name"\:"Proselyte cuisse","quantity"\:1.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"null","quantity"\:0.0,"fuzzy"\:false},{"id"\:7462.0,"name"\:"Barrows gloves","quantity"\:1.0,"fuzzy"\:false},{"id"\:4097.0,"name"\:"Mystic boots","quantity"\:1.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"null","quantity"\:0.0,"fuzzy"\:false},{"id"\:2572.0,"name"\:"Ring of wealth","quantity"\:1.0,"fuzzy"\:false},{"id"\:-1.0,"name"\:"","quantity"\:0.0,"fuzzy"\:false}],"rune_pouch"\:[{"id"\:562.0,"name"\:"Chaos","quantity"\:2121.0,"fuzzy"\:false,"stackCompare"\:"None"},{"id"\:555.0,"name"\:"Water","quantity"\:3878.0,"fuzzy"\:false,"stackCompare"\:"None"},{"id"\:560.0,"name"\:"Death","quantity"\:800.0,"fuzzy"\:false,"stackCompare"\:"None"}],"additionalFilteredItems"\:{},"name"\:"Dust Devils","notes"\:"","highlightColor"\:{"value"\:-65536.0,"falpha"\:0.0},"highlightDifference"\:false,"filterBank"\:false,"unorderedHighlight"\:false,"spellBook"\:0.0,"Id"\:9.223372036854776E18,"favorite"\:false}]`

**Comment by dillydill123** [comment] 2021-10-06 03:33
It would be the email associated with RuneLite. Unfortunately I wasn't able to reproduce the issue. The setups loaded fine for me:

![image](https://user-images.githubusercontent.com/15637422/136136409-ad46edd4-d9eb-47e6-97c5-26d1025086bd.png)

Just to get the low hanging fruit out of the way. Are you sure you are logged in to the account in which the settings.properties is associated?

**Comment by diogo-felix-martins** [comment] 2021-10-09 13:46
I've recently changed to Manjaro and have the same problem. I'm logged in, there are inventorysetups.setups in the file but none shows up. This only happens with the runelite installed from AUR (https://aur.archlinux.org/packages/runelite/), using the .appImage from runelite.net works normally.

**Comment by dillydill123** [comment] 2021-10-09 19:50
Unfortunately I don't have a Mac or linux to debug with. Is anyone able to debug this issue in IntelliJ? Basically there is an exception when serializing the json data for the setups and as a result it defaults to empty setup list. Your setups won't disappear unless you overwrite them by making a new setup or editing the config

**Comment by dillydill123** [comment] 2021-10-09 19:58
I thought it might be that there are '\\' in the settings but I can see other plugins also have this.

**Comment by dillydill123** [comment] 2021-10-09 22:28
That doesn't really add up to me... If it was a permissions issue it would be present in other plugins too no?

**Comment by diogo-felix-martins** [comment] 2021-10-10 07:32
That's true, and the setups seem to be the only thing that doesn't load. I've edited other settings in this plugin and they are saved after relaunching.

How can i debug the plugin to find out the problem?

**Comment by dillydill123** [comment] 2021-10-10 17:24
@diogo-felix-martins 

In the loadConfig() function, please confirm that the exception is being caught and please print out the message to see what the cause is. Try to reproduce the error as simply as possible (only have one setup if possible).

**Comment by Jack-Bruce-Dev** [comment] 2021-10-13 13:22
> @Jack-Bruce-Dev are you able to debug in IntelliJ?

Yes I can, I will take a look now. Let me know if you want to connect on the issue?

**Comment by dillydill123** [comment] 2021-10-14 23:11
After much debugging with @Jack-Bruce-Dev and @diogo-felix-martins, the bug has been found. It turns out the issue was related to JDK versions. I've prepared a fix and submitted a update for the plugin (v1.12.2). Once this update goes through hopefully the problem will be gone for good and I will close this ticket. Feel free to reopen if it still occurs afterwards. FYI as long as you didn't overwrite your settings by creating a new setup once they disappeared, your setups will still exist and load properly. If you did do this, check to see if you have a back up! I apologize for the inconvenience if you lost your setups :(

Here's a brief explanation of the bug. Anyone running with a JDK version of 16+ would encounter this problem. Basically deserialization of the Java AWT Color class would fail due to a problem in the gson library. This would cause the entire setup deserialization to fail, so setups would be empty on startup. Users with newer machines are more likely to encounter this problem due to JDK versions being more up to date. Thankfully the RuneLite devs already encountered this problem before, and they provide their own gson which I injected into Inventory Setups (as opposed to creating my own instance). Their gson has a fix for this issue, likely a type adapter, but I didn't look too much into it.

This also explains why different environments had different behavior. Many users have an older JDK in IntelliJ. So the bug would not show up in a Debug environment. I was able to reproduce the bug and test a fix by switching JDK versions in IntelliJ. Of course this explanation is all useless unless the bug is actually gone after this update. So I'll shut up now :)

**Comment by dillydill123** [comment] 2021-10-17 22:27
The fix has been merged and is available now in v1.12.2!

I apologize for the inconvenience if you lost your setups. Here's what you can do to potentially recover them if they are gone:

- First, check all the settings.properties files (there will be the local one in the users .runelite folder, and cloud ones in the .runelite/profiles folder). The files that have a date appended are backups, and probably contain your missing setup information. Copy the entire line that starts with "inventorysetups.setups" to a new text file for the time being. Note that you should copy the entire text from "inventorysetups.setups" to the closing square bracket "]". This line should contain setup information and not just empty brackets "[]". If it does just contain "[]", check other files.
- Next, log out of RuneLite so your local settings will be applied. Make sure to install inventory setups if it's not installed on your local settings. After you log out make sure to close the client.
- Open up the **local settings.properties** file in your .runelite folder. The path should look like .runelite/settings.properties
- Look for the line "inventorysetups.setups" inside the local settings.properties file, and replace it with what you copied earlier. If this line does not exist in the local settings.properties file, just paste it on a new line at the bottom of the file.
- Open RuneLite again and open Inventory Setups. You should see all your settings now. If you don't check to make sure you copied the information correctly to the correct file. Once you can see your setups, right click the green import icon in the top right and select "mass export". This will mass export your setups to file.
- Next, log into RuneLite with your cloud profile and open up inventory setups. You should see nothing if your setups are gone. Right click the green import icon in the top right and select "mass import". This will mass import the setups back into your cloud profile.
- You should now have your setups back in your cloud profile! Before closing your client, make sure you wait at least 1 minute for it to sync with the cloud. From there you should be good to go.

**Closed by dillydill123** 2021-10-17 22:27 UTC
