### ISSUE TITLE
Feature Request: Highlight (or filter) items in bank

### ISSUE THREAD

**Issue by iawhd** [dillydill123/inventory-setups#1] opened 2019-12-27 01:23 UTC
Could a button be added to mark the items in the bank like the Inventory tags plugin to speed up withdrawal, or alternatively filter items in the bank like the bank tags plugin?

**Comment by dillydill123** [comment] 2019-12-27 08:23
It is possible to do this, although I think I would be reproducing a lot of the same work that the bank tab plugin does. I can look and see how complicated it would be. In the meantime, you can use the bank tabs together with inventory setups, and it should give you the same effect.

**Comment by iawhd** [comment] 2019-12-27 11:47
Thanks for responding! I don't know how much access the Rl devs give you through the plugin hub but I believe my suggestion below would work without too much effort:

Would it be possible to automatically create bank tags when a setup is saved? 

I know that the bank tags are essentially just a string of item id's like this:

`Currency,619,619,995,1464,2996,4067,4278,6183,6306,6529,8851,8951,9474,11849,12012,13204,13307,20527,21341,21555,21656,22207,22820`

In theory it should be pretty easy to implement a 'copy bank tag' button which puts the code onto the users clipboard so that they can paste it into the bank tags interface.

**Comment by dillydill123** [comment] 2019-12-28 05:41
That would be really simple to add. I'm running out of real estate for extra buttons on the Inventory Setup Panels. Perhaps I can make the export button open a sub menu where you choose to export setup data (json), or just export to csv in the way bank tags wants it. although I'm questioning how useful this is because you can right click the inventory/equipment icons in the bank and tag your inventory/equipment that way:

![image](https://user-images.githubusercontent.com/15637422/71539502-d1883d80-290a-11ea-9fcf-71c19a89e991.png)

**Comment by dillydill123** [comment] 2019-12-30 08:17
I've made some considerable progress in investigating filtering. I think I'll be able to implement it in the plugin.

**Comment by iawhd** [comment] 2019-12-30 09:15
That's great! Thanks for looking into it man

**Comment by dillydill123** [comment] 2019-12-31 07:48
Feature has been implemented. It will be in the next update of the plugin.

**Closed by dillydill123** 2019-12-31 07:48 UTC
