### ISSUE TITLE
Hard Tier Diary Items wrong in Search

### ISSUE THREAD

**Issue by Nismm** [dillydill123/inventory-setups#69] opened 2020-12-25 01:00 UTC
Searching for Diary items when updating setups via "Update Slot from Search" lists all Hard Tier items without there 3 counterpart such as:

"Ardougne Cloak" instead of "Ardougne Cloak 3"
"Karamja Gloves" instead of "Karamja Gloves 3"

Didnt use to be an issue but with fuzzy now doesnt detect the item as the correct item. Items should either have name updated or fuzzy option corrected if this makes sense?

**Comment by dillydill123** [comment] 2020-12-25 01:44
Unfortunately I cannot do anything about the weirdness of the item search. I just use RuneLite's API for that. However, I'm unable to reproduce the issue:

![qvcmCGpylH](https://user-images.githubusercontent.com/15637422/103113396-7f1a5380-4628-11eb-82eb-2e78b17a6e03.gif)

It seems to be working fine for me. Can you check that you are on version 1.9.1?
![image](https://user-images.githubusercontent.com/15637422/103113440-b7ba2d00-4628-11eb-8b33-7a407c868548.png)

This may have been the case in 1.9 before the bug fix. Try restarting your client.

**Comment by dillydill123** [comment] 2021-01-16 21:08
Any updates? Else I will close the issue

**Closed** 2021-01-18 16:54 UTC
