### ISSUE TITLE
On-Off Glitching

### ISSUE THREAD

**Issue by tstumpenhusen** [dillydill123/inventory-setups#17] opened 2020-01-23 06:23 UTC
After installing, all features worked. I then got logged out automaticly (maybe with bank filter on, not sure). From there on the enable-thing in the plugins-menu flickered on and off very quickly. I could fix that one by logging back in, i thing (maybe by restarting the client. I was unable to switch it on or off manually.

**Comment by dillydill123** [comment] 2020-01-23 15:11
Are you able to reproduce this issue? I couldn't get it to happen. I let myself get logged out while the bank was open with filtering and I had no problems.

**Comment by dillydill123** [comment] 2020-03-17 01:06
Was not able to reproduce. Closing. If you can reproduce please reopen.

**Closed by dillydill123** 2020-03-17 01:06 UTC
Labels: invalid, question
