### ISSUE TITLE
Loadouts Not Saving

### ISSUE THREAD

**Issue by Dreamscape123** [dillydill123/inventory-setups#155] opened 2022-08-18 08:32 UTC
Hello!

First off let me say that I'm a huge fan of this plugin and it's one of the greatest on Runelite.

This week I probably spent about 6 hours or so redo-ing most of my loadouts and then went to restart Runelite tonight. when I got back into the game I found that none of the revisions I had done were saved, it was showing my old loadouts. Now I've been testing it and it feels like my loadouts are frozen in time. it does not save when I either add or remove any loadouts after restarting Runelite. I've tried this multiple times with no change. Do you know about this issue or any solutions to my problem?

Thanks in advance,

James

**Comment by dillydill123** [comment] 2022-08-18 13:43
Yes, I discovered this problem recently and have been working on a fix. The problem is that RuneLite has a limit on how long a single line can be in the settings.properties file (where all the setups are stored). When I first made inventory setups, I used a really inefficient way of storing the data and this is causing that line to be too long for RuneLite. The fix I’m working on is to compress the data stored in the line so more setups will fit. This will hopefully allow for a lot more setups to fit in a single line. If this proves to be limiting I will have to put each setup data on a separate line which is a more complicated solution.

I really apologize for you losing all that time redoing your setups! For now if you are creating setups I recommend exporting them before getting off so you can import them later.

**Comment by Dreamscape123** [comment] 2022-08-18 16:45
I don't know if this is possible or not, but would you be interested in testing solutions out on my runelite?

**Comment by asphalt8247q** [comment] 2022-08-18 18:53
Wanted to say I'm having the same issues - tried to delete a few setups but nothing :( Thanks for looking into it dream. Appreciate the work you have and continue to put into this plugin!

**Comment by asphalt8247q** [comment] 2022-08-18 18:55
Wanted to say I'm having the same issues - tried to delete a few setups but nothing :( Thanks for looking into it dilly. Appreciate the work you have and continue to put into this plugin!

**Comment by dillydill123** [comment] 2022-08-18 21:51
@Dreamscape123 it won't be necessary. I currently have the solution developed and I'm in the testing phase. With the new optimizations I'm able to add ~350 setups before the limit is hit.

**Comment by Dreamscape123** [comment] 2022-08-18 23:57
@dillydill123 sorry for pestering, but is there a way I could volunteer to be in this testing phase? I'm rather reliant on the inventory setups plugin and don't really know what to do since it's mine seem like they're stuck as is.

**Comment by dillydill123** [comment] 2022-08-19 00:13
@Dreamscape123 I appreciate the offer. If you have experience with development of RuneLite plugins, then you can help me. If not, just hold tight and I will have a fix soon. If you want to send me your setupsx I can test those. It’s located in your settings.properties for your RuneLite account. I need the whole line “inventorySetups.setups”. It should be a long line.

**Comment by Dreamscape123** [comment] 2022-08-19 03:57
I have no runelite development experience, just more so offering my situation as a guinea pig for testing. Mostly trying to get my inventory setups working again as soon as possible. I don't know if this is related or not but i tried exporting a loadout and when i tried to import it back in i kept getting an "Invalid section data." error. Attached is my inventorysetups.setups information, it was a long line. Also i'm pretty new to github, but I wanted to ask if there is a way I can donate money to you for helping me out with this? I'm more than happy to send money your way.


[inventorysetups.setups.txt](https://github.com/dillydill123/inventory-setups/files/9379084/inventorysetups.setups.txt)
.

**Comment by Dreamscape123** [comment] 2022-08-19 04:09
Just to make sure i pulled that from the correct place, i see that i have 2 settings.properties files. one in the .runelite folder and one in the profiles folder. I pulled it from the profiles folder.

**Comment by dillydill123** [comment] 2022-08-19 04:17
It sounds like you have the section mode on and trying to import a setup. Switch to non-section mode and try to import it again. If that doesn't work please put the data here.

I tested your setups file (you gave me the correct one) and with the update it's now well below the limit. The limit RuneLite gives is 262144 and before your setups were at 510621. This is why even after deleting setups it wouldn't sync. You would have to delete over half your setups! After the update your data is sitting at 107283, meaning you could have more than double the setups and still be decently under the limit. So rest assured the update will fix the issue. I'm also keeping the old data there in case anything goes wrong I can make a change to revert back to how it was done before until I fix it. I would recommend exporting your setups regardless.

The change I'm making is going to break Bank Tag Layouts. Therefore I am waiting for him to have a fix so we can both update our plugins at the same time and minimize people making issues about Bank Tag Layouts being broken :) 

There is a donation link in the support and suggestions section here: https://github.com/dillydill123/inventory-setups#inventory-setups. Totally optional and any amount is appreciated.

**Comment by Dreamscape123** [comment] 2022-08-19 04:28
I'm an idiot and had the section mode enabled, I turned it off and it worked. 

Glad to hear that my setups file worked! Also, that makes complete sense that you'll want to wait for the bank tag layouts update as well since I'm sure lots of players use them both together. Do you have an idea of how long it'll take for that update to go live? Also, I've never really thought about how plugins update, I'm assuming it's automatically since I've never manually clicked to update any of them.

I found the link and tried sending you $100 but my bank flagged the charge as fraudulent and locked my card, ffs. Once I get that fixed I'll send it your way. Thank you so much for your help and all that you do for this community!!!

**Comment by dillydill123** [comment] 2022-08-19 04:39
That's extremely generous of you and as I mentioned before totally optional. Don't feel obligated. Thank you.

I'm in discussions with the creator of the plugin and he's currently working on it so I'm sure this weekend we will have it in. The hub plugins update automatically. Inventory Setups has a patch window that appears for every new update. That's how you'll know when the plugin has updated.

**Comment by dillydill123** [comment] 2022-08-19 21:25
Pullrequest has been made so once the RuneLite admins review and approve it the update will go through. https://github.com/runelite/plugin-hub/pull/3215

**Comment by dillydill123** [comment] 2022-08-20 18:34
The pull request was merged so the update is now live. I'm leaving this issue open in case you see any problems. Please let me know if you have any issues and if the problem appears again.

**Comment by Dreamscape123** [comment] 2022-08-21 02:56
Hey, thank you for getting the update out so quickly, When i restarted my runelite it didn't sync so i lost my updates for this week and had to reimport them, but verified that they're now saving when i do another restart.

However i'm now running into another issue. Before this update i had filtered all of my loadouts into different section folders, but now with this update they're still there as well as all of them are also listed in the unassigned section. so it looks like I have 2 copies of each loadout. I can add any loadout from unassigned to a section, but it isn't removing it from the unassigned section. Also when i try to just delete a loadout from the unassigned section it's deleting it from all sections.

**Comment by dillydill123** [comment] 2022-08-21 03:07
Can you send a screenshot? If you have a bunch of setups and you import those setups again, it will make duplicate ones with a number attached to the end.

**Comment by Dreamscape123** [comment] 2022-08-21 03:49
This issue was both before and after I imported those setups. It's kinda hard to take a good screenshot that shows the issue. But yeah i have a duplicate of every setup and i can't remove them from the unassigned section
![loadouts_bug](https://user-images.githubusercontent.com/60309633/185774597-23f83b20-d27f-4a7c-927a-0ae78b21139c.png)
.

**Comment by dillydill123** [comment] 2022-08-21 04:16
Ok, it does look like an issue so I'm trying to reproduce it with no luck. If you restart your client, does it show duplicates?

**Comment by Dreamscape123** [comment] 2022-08-21 04:19
yeah, it stays like that even when I restart. idk if this is relevant to the issue, but i use runelite through the Jagex launcher

**Comment by dillydill123** [comment] 2022-08-21 04:22
Can you send me your settings.properties info again? This time the info will be under `inventorysetups.setupsV2` The whole line

**Comment by dillydill123** [comment] 2022-08-21 04:32
Also, I need your `inventorysetups.sections` line as well.

**Comment by dillydill123** [comment] 2022-08-21 04:55
Ok I'm able to reproduce the issue. It seems to be occurring only when alphabetical mode is on. Investigating now

**Comment by dillydill123** [comment] 2022-08-21 06:08
I found the issue and have fixed it. I was refactoring some code and made a mistake in some logic but it's working on my end. The good news is the internal data is not affected. It was just the logic for determining what setups to display in the Unassigned section was incorrect. I'll make an update request soon.

**Comment by Dreamscape123** [comment] 2022-08-23 03:01
Thank you so much for helping out with everything and i was able to finally get that donation sent over to you! Also sorry for breaking your plugin multiple times.

**Comment by dillydill123** [comment] 2022-08-23 04:40
That's extremely generous of you and I really appreciate it! Just as an FYI I've made a pull request to fix some of the minor bugs that came from this patch so lookout for 1.14.1 to fix the duplicate setups in unassigned section soon (once the RL admins review it). If you find anymore issues let me know

**Comment by dillydill123** [comment] 2022-08-26 17:13
The update is out, so please let me know if there are any other issues you notice with a new issue. I finally got my hands on the new rune pouch and unfortunately there's a small issue I'm making a hot fix for at the moment.

**Closed by dillydill123** 2022-08-26 17:13 UTC
